#!/bin/csh -f


set damp = `cat S40.LS.ttwt.50.splwt.1000.eta=0.001.cmbk.1.res.info | colgrep -c 2`
set nunk = `cat S40.LS.ttwt.50.splwt.1000.eta=0.001.cmbk.1.res.info | colgrep -c 4`
set n   = $#nunk

foreach mod ( *.sph )

  set d = $mod:r:e
  set a1 = `echo $d | cut -d 'd' -f 1` 
# echo $mod d= $d damp= $damp[2] a1= $a1
  @ i=0
  while ( $i < $n) 
    @ i++
    set a2 = `calc $damp[$i] x 1.e6`
    set a = `calc $a1 - $a2`
    set a = `calc abs $a`
#   echo a= $a a1= $a1 a2= $a2
    if ( `calc $a \< 0.1` ) then
#     echo mod= $mod damp= $damp[$i] n= $nunk[$i] a= $a a1= $a1 a2= $a2
      set nint = `calc int $nunk[$i]`
      mv $mod S40.n=$nint.sph
    endif
  end
end
